### ISSUE TITLE
Change VOE Link Fetching from Selenium to easy Logic back

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#33]
https://github.com/wolfswolke/aniworld_scraper/commit/92a374d875f2c9b127da6378d22b5cee13d3cd46

Can you Update VOE Logic to this commit for without Selenium Use

**Comment by speedyconzales** [comment]
why?

**Comment by shedowe19** [comment]
This is faster Logic as then i must wait the Selenium started and Fetch the Link

**Comment by speedyconzales** [comment]
Indeed a couple seconds faster... and more error prone. Cause when VOE does change something again on this part you have to adapt the code again.. and again.. and again. The selenium approach is less error prone in regard to redirects and javascript stuff in the middle. As long as the webpage at the end does not change its structure then you are fine. Otherwise you have to adapt the code either way

Since it is a mandatory dependency for bs.to stuff, I do not care using the selenium approach even it is less efficient. Hopefully that saves me some code adaptions when VOE is changing their current javascript stuff that they use for redirecting. Selenium does not care about it, it will just run it
