### ISSUE TITLE
[Feature Request] Add Title / Name for the Episodes

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#37]
Name for the Episodes in Name and the TMDB ID for better sorting and analysis in Jellyfin

this is One Piece example: (scheme: S01E01 - Hier kommt Ruffy, der künftige König der Piraten!)

**Comment by shedowe19** [comment]
@speedyconzales can you look on to this?

this is One Piece example: (scheme: One Piece - S01E01 - Hier kommt Ruffy, der künftige König der Piraten!)

**Comment by speedyconzales** [comment]
What is better then? What are the benefits of this change?
scraping the episode name and including it in the file name has no benefit according to the docs https://jellyfin.org/docs/general/server/media/shows/ 
jellyfin does not parse the episode name in the file. since jellyfin does pull the metadata from the database source (which also is dependent on the user, you can choose TMDB or TVDB or something else). so season number and episode number are sufficient to identify episodes

and there lies your problem. the episode numbers of season 2 and following are not counted up further, but always start at 1 per season. but this is different in the TMBD source. the TMDB expects season 2 to start with episode 62. therefore jellyfin cannot match this. (this is also a very specific scenario for the one piece anime, in most cases every new season does start fresh with the numbering of their episodes) so you have to rename the episodes according to the database. if you had TVDB then all episodes of each season would start at 1 but then you would have to rearrange the episodes differently because the seasons are cut differently. The task of renaming the episodes according to the underlying database is not a task for the series scraper

Since there is also a debate in the community regarding which database to use... e.g.: I personally do not use TMDB for shows and animes. So I would label this as personal preference

One thing that would actually help avoiding mandatory manual work is a consistent use of a database as source. But aniworld.to and s.to both are a mess regarding this. sometimes they do not match either TMDB or TVDB
